### ISSUE TITLE
Upstream breaking changes due to mixed dimensional meshes

### ISSUE THREAD

**Issue by francesco-ballarin** [niravshah241/MDFEniCSx#1]
Hi Nirav,
this commit in RBniCSx https://github.com/RBniCS/RBniCSx/commit/da356d4a064a41441d6635e75570b3b8f9a70fb4 is due to upstream breaking changes introduced in https://github.com/FEniCS/dolfinx/pull/2597. You may want to replicate this small update here too if you target to stay up-to-date with dolfinx `main` branch.

**Comment by niravshah241** [comment]
thanks Francesco. See niravshah241/MDFEniCSx@e1ea70f
