### ISSUE TITLE
Negative Impact on Mesh when using is_deformation = False possibly due to round-off error

### ISSUE THREAD

**Issue by nhornischer** [niravshah241/MDFEniCSx#3]
Test problem: Navier-Stokes with parametrized domain geometry

Problem: Solver is not always converging for mesh-deformation with is_deformation = False, but converges when defining the deformation simply by subtracting the original values and using is_deformation = True.
Likely, that this behavior is caused by round-off error in the mesh-deformation-algorithm.

**Comment by niravshah241** [comment]
Hello @nhornischer , Could you post a minimum working example (MWE)?

**Comment by nhornischer** [comment]
`from mpi4py import MPI
from mdfenicsx.mesh_motion_classes import HarmonicMeshMotion

import dolfinx
import numpy as np
import math
import gmsh

gmsh.initialize('', False)

lc = 0.04
gdim = 2

gmsh.model.geo.addPoint(0., 0., 0., lc, 1)
gmsh.model.geo.addPoint(1., 0., 0., lc, 2)
gmsh.model.geo.addPoint(1., 1., 0., lc, 3)
gmsh.model.geo.addPoint(0., 1., 0., lc, 4)

gmsh.model.geo.addLine(1, 2, 1)
gmsh.model.geo.addLine(2, 3, 2)
gmsh.model.geo.addLine(3, 4, 3)
gmsh.model.geo.addLine(4, 1, 4)

gmsh.model.geo.addCurveLoop([1, 2, 3, 4], 1)
gmsh.model.geo.addPlaneSurface([1], 1)

gmsh.model.geo.synchronize()

# Refine at the top
distance_field = gmsh.model.mesh.field.add("Distance")
gmsh.model.mesh.field.setNumbers(distance_field, "EdgesList", [3])
refinement_field = gmsh.model.mesh.field.add("Threshold")
gmsh.model.mesh.field.setNumber(refinement_field, "IField", distance_field)
gmsh.model.mesh.field.setNumber(refinement_field, "LcMin", lc/4)
gmsh.model.mesh.field.setNumber(refinement_field, "LcMax", lc)
gmsh.model.mesh.field.setNumber(refinement_field, "DistMin", 0.0)
gmsh.model.mesh.field.setNumber(refinement_field, "DistMax", 0.3)

gmsh.model.mesh.field.setAsBackgroundMesh(refinement_field)

gmsh.model.mesh.generate(gdim)
gmsh.model.mesh.setOrder(2)
gmsh.model.mesh.optimize("Netgen")

# Extract edges and surfaces to add physical groups
surfaces = gmsh.model.getEntities(dim=gdim)
edges = gmsh.model.getBoundary(surfaces)

# Subdomains markings
for i in range(1, len(surfaces)+1):
    gmsh.model.addPhysicalGroup(gdim, [surfaces[i-1][1]], surfaces[i-1][1])
# External boundaries markings
for i in range(1, len(edges)+1):
    gmsh.model.addPhysicalGroup(gdim-1, [edges[i-1][1]], edges[i-1][1])

gmsh.write("mesh.msh")

gmsh.fltk.run()

gmsh.finalize()

# Import mesh in dolfinx
gmsh_model_rank = 0
mesh_comm = MPI.COMM_WORLD
mesh, cell_tags, facet_tags = dolfinx.io.gmshio.read_from_msh(
    "mesh.msh", mesh_comm, gmsh_model_rank, gdim=gdim)

with dolfinx.io.XDMFFile(MPI.COMM_WORLD, "mesh.xdmf", "w") as mesh_file_xdmf:
    mesh_file_xdmf.write_mesh(mesh)
    mesh_file_xdmf.write_meshtags(cell_tags)
    mesh_file_xdmf.write_meshtags(facet_tags)

# Mesh deformation parameters
mu = np.array([1.0, 2/np.sqrt(3), math.pi/3])

# Read unit square mesh with Triangular elements
mesh_comm = MPI.COMM_WORLD
gdim = 2
gmsh_model_rank = 0
mesh, cell_tags, facet_tags = dolfinx.io.gmshio.read_from_msh("mesh.msh", mesh_comm, gmsh_model_rank, gdim = gdim)
boundary_markers = [1, 2, 3, 4]

# Boundary conditions for custom mesh deformation (not for problem)
def u_bc_bottom(x): return (mu[0] * x[0] - x[0],x[1] - x[1])
def u_bc_right(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1] * x[1] -x[0], np.sin(mu[2]) * mu[1] * x[1]-x[1])
def u_bc_top(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1]-x[0], np.sin(mu[2]) * mu[1] +  0.0 * x[1]-x[1])
def u_bc_left(x): return (np.cos(mu[2]) * mu[1] * x[1] -x[0], np.sin(mu[2]) * mu[1] * x[1]-x[1])

with HarmonicMeshMotion(mesh, facet_tags, boundary_markers, [u_bc_bottom, u_bc_right, u_bc_top, u_bc_left], reset_reference=True, is_deformation=True) as mesh_class:
    coordinates_deformation = mesh.geometry.x.copy()
    with dolfinx.io.XDMFFile(mesh.comm, "test_deformation.xdmf", "w") as xdmf:
        xdmf.write_mesh(mesh)
        xdmf.write_meshtags(cell_tags)
        xdmf.write_meshtags(facet_tags)

# Boundary conditions for custom mesh deformation (not for problem)
def u_bc_bottom(x): return (mu[0] * x[0],x[1])
def u_bc_right(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1] * x[1], np.sin(mu[2]) * mu[1] * x[1])
def u_bc_top(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1], np.sin(mu[2]) * mu[1] +  0.0 * x[1])
def u_bc_left(x): return (np.cos(mu[2]) * mu[1] * x[1] , np.sin(mu[2]) * mu[1] * x[1])

with HarmonicMeshMotion(mesh, facet_tags, boundary_markers, [u_bc_bottom, u_bc_right, u_bc_top, u_bc_left], reset_reference=True, is_deformation=False) as mesh_class:
    coordinates_nonDeformed = mesh.geometry.x.copy()
    with dolfinx.io.XDMFFile(mesh.comm, "test_coordinates.xdmf", "w") as xdmf:
        xdmf.write_mesh(mesh)
        xdmf.write_meshtags(cell_tags)
        xdmf.write_meshtags(facet_tags)

print("All close? ", np.allclose(coordinates_deformation,coordinates_nonDeformed))
print("Maximal Difference between coordinates: ", np.max(coordinates_deformation-coordinates_nonDeformed))
print("Mean Difference between coordinates: ", np.mean(coordinates_deformation-coordinates_nonDeformed))`

**Comment by nhornischer** [comment]
from mpi4py import MPI
from mdfenicsx.mesh_motion_classes import HarmonicMeshMotion

import dolfinx
import numpy as np
import math
import gmsh

gmsh.initialize('', False)

lc = 0.04
gdim = 2

gmsh.model.geo.addPoint(0., 0., 0., lc, 1)
gmsh.model.geo.addPoint(1., 0., 0., lc, 2)
gmsh.model.geo.addPoint(1., 1., 0., lc, 3)
gmsh.model.geo.addPoint(0., 1., 0., lc, 4)

gmsh.model.geo.addLine(1, 2, 1)
gmsh.model.geo.addLine(2, 3, 2)
gmsh.model.geo.addLine(3, 4, 3)
gmsh.model.geo.addLine(4, 1, 4)

gmsh.model.geo.addCurveLoop([1, 2, 3, 4], 1)
gmsh.model.geo.addPlaneSurface([1], 1)

gmsh.model.geo.synchronize()

# Refine at the top
distance_field = gmsh.model.mesh.field.add("Distance")
gmsh.model.mesh.field.setNumbers(distance_field, "EdgesList", [3])
refinement_field = gmsh.model.mesh.field.add("Threshold")
gmsh.model.mesh.field.setNumber(refinement_field, "IField", distance_field)
gmsh.model.mesh.field.setNumber(refinement_field, "LcMin", lc/4)
gmsh.model.mesh.field.setNumber(refinement_field, "LcMax", lc)
gmsh.model.mesh.field.setNumber(refinement_field, "DistMin", 0.0)
gmsh.model.mesh.field.setNumber(refinement_field, "DistMax", 0.3)

gmsh.model.mesh.field.setAsBackgroundMesh(refinement_field)

gmsh.model.mesh.generate(gdim)
gmsh.model.mesh.setOrder(2)
gmsh.model.mesh.optimize("Netgen")

# Extract edges and surfaces to add physical groups
surfaces = gmsh.model.getEntities(dim=gdim)
edges = gmsh.model.getBoundary(surfaces)

# Subdomains markings
for i in range(1, len(surfaces)+1):
    gmsh.model.addPhysicalGroup(gdim, [surfaces[i-1][1]], surfaces[i-1][1])
# External boundaries markings
for i in range(1, len(edges)+1):
    gmsh.model.addPhysicalGroup(gdim-1, [edges[i-1][1]], edges[i-1][1])

gmsh.write("mesh.msh")

gmsh.fltk.run()

gmsh.finalize()

# Import mesh in dolfinx
gmsh_model_rank = 0
mesh_comm = MPI.COMM_WORLD
mesh, cell_tags, facet_tags = dolfinx.io.gmshio.read_from_msh(
    "mesh.msh", mesh_comm, gmsh_model_rank, gdim=gdim)

with dolfinx.io.XDMFFile(MPI.COMM_WORLD, "mesh.xdmf", "w") as mesh_file_xdmf:
    mesh_file_xdmf.write_mesh(mesh)
    mesh_file_xdmf.write_meshtags(cell_tags)
    mesh_file_xdmf.write_meshtags(facet_tags)

# Mesh deformation parameters
mu = np.array([1.0, 2/np.sqrt(3), math.pi/3])

# Read unit square mesh with Triangular elements
mesh_comm = MPI.COMM_WORLD
gdim = 2
gmsh_model_rank = 0
mesh, cell_tags, facet_tags = dolfinx.io.gmshio.read_from_msh("mesh.msh", mesh_comm, gmsh_model_rank, gdim = gdim)
boundary_markers = [1, 2, 3, 4]

# Boundary conditions for custom mesh deformation (not for problem)
def u_bc_bottom(x): return (mu[0] * x[0] - x[0],x[1] - x[1])
def u_bc_right(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1] * x[1] -x[0], np.sin(mu[2]) * mu[1] * x[1]-x[1])
def u_bc_top(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1]-x[0], np.sin(mu[2]) * mu[1] +  0.0 * x[1]-x[1])
def u_bc_left(x): return (np.cos(mu[2]) * mu[1] * x[1] -x[0], np.sin(mu[2]) * mu[1] * x[1]-x[1])

with HarmonicMeshMotion(mesh, facet_tags, boundary_markers, [u_bc_bottom, u_bc_right, u_bc_top, u_bc_left], reset_reference=True, is_deformation=True) as mesh_class:
    coordinates_deformation = mesh.geometry.x.copy()
    with dolfinx.io.XDMFFile(mesh.comm, "test_deformation.xdmf", "w") as xdmf:
        xdmf.write_mesh(mesh)
        xdmf.write_meshtags(cell_tags)
        xdmf.write_meshtags(facet_tags)

# Boundary conditions for custom mesh deformation (not for problem)
def u_bc_bottom(x): return (mu[0] * x[0],x[1])
def u_bc_right(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1] * x[1], np.sin(mu[2]) * mu[1] * x[1])
def u_bc_top(x): return (mu[0]* x[0] + np.cos(mu[2]) * mu[1], np.sin(mu[2]) * mu[1] +  0.0 * x[1])
def u_bc_left(x): return (np.cos(mu[2]) * mu[1] * x[1] , np.sin(mu[2]) * mu[1] * x[1])

with HarmonicMeshMotion(mesh, facet_tags, boundary_markers, [u_bc_bottom, u_bc_right, u_bc_top, u_bc_left], reset_reference=True, is_deformation=False) as mesh_class:
    coordinates_nonDeformed = mesh.geometry.x.copy()
    with dolfinx.io.XDMFFile(mesh.comm, "test_coordinates.xdmf", "w") as xdmf:
        xdmf.write_mesh(mesh)
        xdmf.write_meshtags(cell_tags)
        xdmf.write_meshtags(facet_tags)

print("All close? ", np.allclose(coordinates_deformation,coordinates_nonDeformed))
print("Maximal Difference between coordinates: ", np.max(coordinates_deformation-coordinates_nonDeformed))
print("Mean Difference between coordinates: ", np.mean(coordinates_deformation-coordinates_nonDeformed))

**Comment by nhornischer** [comment]
Added MWE that shows the round-off error between the mesh-deformation algorithms.

[test.txt](https://github.com/niravshah241/MDFEniCSx/files/11757050/test.txt)

**Comment by niravshah241** [comment]
The error shown in your problem is close to machine precision, which unfortunately cannot be avoided. The other option is to rather try with incremental mesh deformation algorithm or adapt the solver.

**Comment by niravshah241** [comment]
Closed by fixing issues in formulation.
